## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 

podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }

resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1000m

persistence:
  size: 16G

auth:
  rootUser: admin
  rootPassword: master77!!   # 10자이상 필수

service:
  type: NodePort

ingress:
  enabled: true
  hostname: minio2.saas.sysmasterk8s.com  
