## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 

postgresql:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 2000m
  pgHbaTrustAll: true

pgpool:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 2000m
  numInitChildren: 512 
  livenessProbe:
    enabled: false
  customLivenessProbe:
    tcpSocket:
      port: postgresql
  readinessProbe:
    enabled: false
  customReadinessProbe:
    tcpSocket:
      port: postgresql

persistence:
  size: 8Gi

service:
  type: NodePort
