apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: server
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  kong-container-health.sh: |-
    #!/bin/bash

    set -o errexit
    set -o nounset
    set -o pipefail


{{- if .Values.adminPassword }}
    # 2022-05 update nginx-kong.conf
    if [[ -f "/opt/bitnami/kong/server/nginx_updated" ]]
    then
        echo "nginx.conf was updated"
    else
        if [[ -f "/opt/bitnami/kong/server/nginx-kong.conf" ]]
        then
            sed -i 's/server_name kong_admin;/server_name kong_admin;\n    auth_basic "admin basic auth";\n    auth_basic_user_file \/opt\/bitnami\/kong\/server\/.htpasswd;/g' /opt/bitnami/kong/server/nginx-kong.conf
            echo "updated" >> /opt/bitnami/kong/server/nginx_updated
            /opt/bitnami/kong/openresty/nginx/sbin/nginx -s reload -p /opt/bitnami/kong/server -c nginx.conf
            echo "nginx.conf is updated"
        else
            echo "no nginx.conf"
        fi
    fi
{{- end }}
    # Load libraries
    . /opt/bitnami/scripts/libos.sh
    . /opt/bitnami/scripts/libkong.sh

    # Load Kong environment variables
    eval "$(kong_env)"

    is_kong_running

  ingress-container-wait-for-kong.sh: |-
    #!/bin/bash

    echo "Waiting for the Kong container to be ready"
    if wait-for-port --timeout={{ .Values.ingressController.proxyReadyTimeout }} --host=127.0.0.1 --state=inuse {{ .Values.kong.containerPorts.proxyHttp }}; then
      echo "Kong container ready"
    else
      echo "Kong not ready after {{ .Values.ingressController.proxyReadyTimeout }} seconds"
      exit 1
    fi

  ingress-container-start.sh: |-
    #!/bin/bash

    . /health/ingress-container-wait-for-kong.sh

    kong-ingress-controller
