name: mariadb
version: 0.1.0
id: 23ea8030-95fe-11ec-b909-0242ac120001
description: "Mariadb by Helm Broker. "
displayName: "Mariadb"
tags: database, sysmasterk8s 
providerDisplayName: bitnami
longDescription: "https://github.com/bitnami/charts/tree/master/bitnami/mariadb/#installing-the-chart"
documentationURL: https://github.com/bitnami/bitnami-docker-mariadb
supportURL: https://bitnami.com/support
imageURL: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png 
bindable: true
