name: rabbitmq 
version: 0.1.1
id: 19dec6c2-9839-11ec-b909-0242ac120001
description: "rabbitmq by Helm Broker. "
displayName: "rabbitmq"
tags: rabbitmq, message queue, AMQP, sysmasterk8s 
providerDisplayName: bitnami
longDescription: "https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq/#installing-the-chart"
documentationURL: https://github.com/bitnami/bitnami-docker-rabbitmq
supportURL: https://bitnami.com/support
imageURL: https://bitnami.com/assets/stacks/rabbitmq/img/rabbitmq-stack-220x234.png
bindable: true
