## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
kubeVersion: 1.20-11
podLabels: { "app":"monitoring-collector", "platform":"platform_service", "taskse":"service_catalog", "taskcl":"backend_service" }

replicaCount: 3 

service:
  type: NodePort
  port: 5672

resources:
  requests:
    memory: 1Gi 
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1000m
