## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
kubeVersion: 1.20-11

replicaCount: 3 

service:
  type: NodePort
  port: 5672

resources:
  requests:
    memory: 1Gi 
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1000m
