## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 

architecture: standalone 

primary:
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: 2000m

