name: postgresql-ha 
version: 0.1.0
id: faefad00-c752-11ec-9d64-0242ac120001
description: "Postgresql-HA by Helm Broker. "
displayName: "Postgresql-HA"
tags: database, sysmasterk8s 
providerDisplayName: bitnami
longDescription: "https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha/#installing-the-chart"
documentationURL: https://github.com/bitnami/bitnami-docker-postgresql
supportURL: https://bitnami.com/support
imageURL: //bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png 
bindable: true
