## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 
podLabels: { "app":"monitoring-collector", "platform":"platform_service", "taskse":"service_catalog", "taskcl":"backend_service" }

replicaCount: 1 

service:
  type: NodePort

zookeeper:
  podLabels: { "app":"monitoring-collector", "platform":"platform_service", "taskse":"service_catalog", "taskcl":"backend_service" }
  service:
    type: NodePort

externalAccess:
  service:
    type: NodePort
  autoDiscovery:
    enabled: true

serviceAccount:
  create: true

rbac:
  create: true

resources:
  requests:
    memory: 200Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 500m
