## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 

podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }

replicaCount: 1 

zookeeper:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 500Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  persistence:
    size: 8Gi

externalAccess:
  enabled: true
  service:
    type: NodePort
    domain: "112.175.114.177"
  autoDiscovery:
    enabled: true 
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
      limits:
        memory: 400Mi 
        cpu: 200m

serviceAccount:
  create: true

rbac:
  create: true

resources:
  requests:
    memory: 500Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

persistence:
  size: 8Gi



