apiVersion: v1
appVersion: "1.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
description: A Helm chart for Kubernetes
name: konga
version: 1.0.0
