## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 

architecture : standalone

master:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi 
      cpu: 200m
 
  service:
    type: NodePort

