## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 
podLabels: { "app":"monitoring-collector", "platform":"platform_service", "taskse":"service_catalog", "taskcl":"backend_service" }

architecture : standalone

master:
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
  service:
    type: NodePort

