## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 
global:
  kubeVersion: 1.20-11 

podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m
persistence:
  size: 8G    
  
livenessProbe:
  failureThreshold: 50
  initialDelaySeconds: 210
  periodSeconds: 210
readinessProbe:
  failureThreshold: 50
  initialDelaySeconds: 210
  periodSeconds: 210

service:
  type: NodePort

mariadb:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 1Gi
      cpu: 1000m
    limits:
      memory: 2Gi
      cpu: 2000m
  persistence:
    size: 8G

