## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 

resources:
  requests:
    memory: 2Gi
    cpu: 1000m
  limits:
    memory: 4Gi
    cpu: 2000m

