name: mariadb-galera
version: 0.1.0
id: 2b829eaa-c5cd-11ec-9d64-0242ac120001
description: "Mariadb-galera by Helm Broker. "
displayName: "Mariadb-galera"
tags: database, sysmasterk8s 
providerDisplayName: bitnami
longDescription: "https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera/#installing-the-chart"
documentationURL: https://github.com/bitnami/bitnami-docker-mariadb-galera 
supportURL: https://bitnami.com/support
imageURL: https://bitnami.com/assets/stacks/mariadb-galera/img/mariadb-galera-stack-220x234.png 
bindable: true
