## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 

postgresql:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 3Gi
      cpu: 1500m
    limits:
      memory: 6Gi
      cpu: 3000m
  pgHbaTrustAll: true

pgpool:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 3Gi
      cpu: 1500m
    limits:
      memory: 6Gi
      cpu: 3000m
  numInitChildren: 1024 
  livenessProbe:
    enabled: false
  customLivenessProbe:
    tcpSocket:
      port: postgresql
  readinessProbe:
    enabled: false
  customReadinessProbe:
    tcpSocket:
      port: postgresql

persistence:
  size: 16Gi

service:
  type: NodePort
