apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterserviceclasses.servicecatalog.k8s.io
  labels:
    svcat: "true"
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: servicecatalog.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: External-Name
          type: string
          jsonPath: .spec.externalName
        - name: Broker
          type: string
          jsonPath: .spec.clusterServiceBrokerName
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties: {} # 여기에 필요한 스키마를 추가해야 합니다.
  scope: Cluster
  names:
    plural: clusterserviceclasses
    singular: clusterserviceclass
    kind: ClusterServiceClass
    categories:
      - all
      - svcat
