apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterservicebrokers.servicecatalog.k8s.io
  labels:
    svcat: "true"
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: servicecatalog.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      subresources: {}
      additionalPrinterColumns:
        - name: URL
          type: string
          jsonPath: .spec.url
        - name: Status
          type: string
          jsonPath: .status.lastConditionState
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties: {} # 여기에 필요한 스키마를 추가해야 합니다.
  scope: Cluster
  names:
    plural: clusterservicebrokers
    singular: clusterservicebroker
    kind: ClusterServiceBroker
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
      - svcat
