apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceplans.servicecatalog.k8s.io
  labels:
    svcat: "true"
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: servicecatalog.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: External-Name
          type: string
          jsonPath: .spec.externalName
        - name: Broker
          type: string
          jsonPath: .spec.serviceBrokerName
        - name: Class
          type: string
          jsonPath: .spec.serviceClassRef.name
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties: {} # 필요한 스키마를 추가하세요
  scope: Namespaced
  names:
    plural: serviceplans
    singular: serviceplan
    kind: ServicePlan
    categories:
      - all
      - svcat