apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceinstances.servicecatalog.k8s.io
  labels:
    svcat: "true"
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: servicecatalog.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties: {} # 필요한 스키마를 추가하세요
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Class
          type: string
          jsonPath: .status.userSpecifiedClassName
        - name: Plan
          type: string
          jsonPath: .status.userSpecifiedPlanName
        - name: Status
          type: string
          jsonPath: .status.lastConditionState
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: serviceinstances
    singular: serviceinstance
    kind: ServiceInstance
    categories:
      - all
      - svcat
