name: postgresql 
version: 0.1.0
id: 9a7d0cc8-cb68-11ec-9d64-0242ac120001
description: "MongoDB by Helm Broker. "
displayName: "MongoDB"
tags: nosql, database, sysmasterk8s 
providerDisplayName: bitnami
longDescription: "https://github.com/bitnami/charts/tree/master/bitnami/mongodb/#installing-the-chart"
documentationURL: https://github.com/bitnami/bitnami-docker-mongodb
supportURL: https://bitnami.com/support
imageURL: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png 
bindable: true
