name: apache
version: 0.1.1
id: dbb4666a-904c-4403-b43e-eb1f0f49f9e1
description: "Apache by Helm Broker. "
displayName: "Apache"
tags: apache, sysmasterk8s 
providerDisplayName: bitnami
longDescription: "https://github.com/bitnami/charts/tree/master/bitnami/apache/#installing-the-chart"
documentationURL: https://github.com/bitnami/bitnami-docker-apache
supportURL: https://bitnami.com/support
imageURL: https://bitnami.com/assets/stacks/apache/img/apache-stack-220x234.png
bindable: true
