## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11

global:
  imageRegistry: registry.saas.sysmasterk8s.com:443


migration:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 4Gi
      cpu: 2000m
    limits:
      memory: 4Gi
      cpu: 2000m

kong: 
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 4Gi
      cpu: 2000m
    limits:
      memory: 8Gi
      cpu: 4000m
  livenessProbe:
    failureThreshold: 50
    initialDelaySeconds: 180 
    periodSeconds: 180 
  readinessProbe:
    failureThreshold: 50
    initialDelaySeconds: 180 
    periodSeconds: 180 

service:
  exposeAdmin: true 
  type: NodePort

ingress:
  enabled: true
  hostname: kong2.saas.sysmasterk8s.com

adminPassword: "master"

konga:
  enabled: true 
  kongAdminPassword: "master"
  kongName: "kong-01"
  kongAdminHttp: 8001

  kongaAdminPassword: "master"

  service:
    type: NodePort
  resource:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 2000m
      memory: 2000Mi

  ingress:
    enabled: true
    hosts:
      - host: konga2.saas.sysmasterk8s.com
        paths: ['']

postgresql:
  auth:
    password: 'master77!!' 
    postgresPassword: 'master77!!'

  primary:
    podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
    resources:
      requests:
        memory: 4Gi
        cpu: 2000m
      limits:
        memory: 8Gi
        cpu: 4000m
    persistence:
      size: 8Gi
      #  service:
      #type: NodePort

