tests:
  image: helm-broker-tests
  dir: /pr/
  tag: PR-136
  securityContext:
    runAsUser: 2000

service:
  type: NodePort
  externalPort: 80
  annotations: {}

deploy:
  annotations: {}

ctrl:
  tmpDirSizeLimit: 1Gi
  resources:
    limits:
      memory: 960Mi
      cpu: 1000m
    requests:
      memory: 320Mi
      cpu: 800m
  internalPort: 8080
  statusPort: 8081
  # enable/disable docs topics support for helm controller
  documentationEnabled: false
  uploadServiceURL: "not-needed-if-APP_DOCUMENTATION_ENABLED-set-to-false"

broker:
  resources:
    limits:
      memory: 760Mi
      cpu: 600m
    requests:
      memory: 320Mi
      cpu: 300m
  internalPort: 8070
  statusPort: 8071
  metricsPort: 8072

webhook:
  image: "registry.sysmasterk8s-v3.com/helm-broker/helm-broker-webhook:0.8"
  imagePullPolicy: IfNotPresent
  securityContext: {runAsUser: 1001}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  minReadySeconds: 1
  annotations:
    sidecar.istio.io/inject: "false"
  healthcheck:
    enabled: false
  # Attributes of the webhook's service resource
  service:
    port: 8443
    targetPort: 8443
  # Webhook resource requests and limits
  # Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      cpu: 1000m
      memory: 200Mi
    limits:
      cpu: 1000m
      memory: 300Mi

defaultAddonsURL: "https://github.com/kyma-project/addons/releases/download/0.15.0/index.yaml"

global:
  containerRegistry:
    path: eu.gcr.io/kyma-project
  # develop mode allows use insecure (http) url for addons configuration
  isDevelopMode: false
  # image pull policy for helm broker broker/controller containers
  image:
    pullPolicy: IfNotPresent
  # paths to docker images
  helm_broker:
    dir: /pr/
    version: PR-190
  helm_controller:
    dir: /pr/
    version: PR-190
  # etcd port uses by helm broker
  etcdClientPort: 2379
