{{- if .Values.kongaAdminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "konga.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels: 
    app.kubernetes.io/name: {{ include "konga.name" . }}
    helm.sh/chart: {{ include "konga.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque 
data:
  konga-admin-password: {{ .Values.kongaAdminPassword | b64enc | quote }}
{{- end }}
