apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "konga.fullname" . }}-data-config
  labels:
    app.kubernetes.io/name: {{ include "konga.name" . }}
    helm.sh/chart: {{ include "konga.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- if .Values.kongaAdminPassword }}
  userdb.data: |-
    module.exports = [
        {     
            "username": "admin",
            "email": "myadmin@some.domain",
            "firstName": "Admin",
            "lastName": "Administrator",
            "admin": true,
            "active" : true,
            "password": "{{ .Values.kongaAdminPassword }}",
        }
    ]
{{- end }}
{{- if .Values.kongAdminPassword }}
  kong_node.data: |-
    module.exports = [
        {
            "name": "Kong",
            "type": "basic_auth",
            "active" : "true",
            "username": "admin",
            "password": "{{ .Values.kongAdminPassword }}",
{{- if .Values.kongName }}
            "kong_admin_url": "http://{{ .Values.kongName }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.kongAdminHttp }}",
{{- end -}}
        }
    ]
{{- end }}
