## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 


podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
resources:
  requests:
    memory: 2Gi
    cpu: 1000m
  limits:
    memory: 4Gi
    cpu: 2000m

service:
  type: NodePort

ingress:
  enabled: true
  hostname: airflow.saas.sysmasterk8s.com

postgresql:
  enabled: true 
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  auth:
    password: 'master77!!'
  primary:
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m
    persistence:
      size: 8G
redis:
  enabled: true
  master:
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m
