## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
kubeVersion: 1.20-11

podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }

replicaCount: 3 

service:
  type: NodePort

zookeeper:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m

externalAccess:
  enabled: true
  service:
    type: NodePort
  autoDiscovery:
    enabled: true
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 500m

serviceAccount:
  create: true

rbac:
  create: true

resources:
  requests:
    memory: 200Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 500m





