## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
master:
  resources:
    requests:
      memory: 96Mi

replica:
  resources:
    requests:
      memory: 96Mi

