kubeVersion: 1.20-11 


podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }

service:
  type: NodePort

web:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 512Mi
      cpu: 1000m
    limits:
      memory: 1024Mi
      cpu: 2000m

scheduler:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 512Mi
      cpu: 1000m
    limits:
      memory: 1024Mi
      cpu: 2000m

worker:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 1Gi
      cpu: 1000m
    limits:
      memory: 2Gi
      cpu: 2000m


postgresql:
  enabled: true 
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  auth:
    password: 'master77!!'
  primary:
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m
    persistence:
      size: 8G

redis:
  enabled: true
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  master:
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m
  persistence:
    size: 8G