name: jupyterhub
version: 0.1.0
id: 1775e441-153f-4192-b5f5-fed16bd65f91
description: "Jupyterhub by Helm Broker. "
displayName: "jupyterhub"
tags: jupyterhub, sysmasterk8s 
providerDisplayName: bitnami
longDescription: "https://github.com/bitnami/charts/tree/master/bitnami/jupyterhub/#installing-the-chart"
documentationURL: https://github.com/bitnami/bitnami-docker-jupyterhub
supportURL: https://bitnami.com/support
imageURL: https://bitnami.com/assets/stacks/jupyterhub/img/jupyterhub-stack-220x234.png
bindable: true
