apiVersion: addons.kyma-project.io/v1alpha1
kind: ClusterAddonsConfiguration
metadata:
  name: rabbitmq-cfg
spec:
  repositories:
    - url: "https://k8s-nexus.spaasta.com/repository/downloads/addons/rabbitmq-0.1.0/index-rabbitmq.yaml"
