apiVersion: addons.kyma-project.io/v1alpha1
kind: AddonsConfiguration
metadata:
  name: redis-cfg
  namespace: redis01
spec:
  repositories:
    - url: "https://raw.githubusercontent.com/infranics/sysk8s/main/redis-0.1.0/index-redis.yaml"
