apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: kafka-03
  namespace: kafka
spec:
  clusterServiceClassExternalName: kafka
  clusterServicePlanExternalName: micro 
  parameters:
    fullnameOverride: kafka-03
    externalAccess:
      service:
        domain: "112.175.114.177"
    global:
      imageRegistry: "registry.systeer.com" 
    zookeeper:
      global:
        imageRegistry: "registry.systeer.com" 
