apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mongodb-03
  namespace: mongodb
spec:
  clusterServiceClassExternalName: mongodb 
  clusterServicePlanExternalName: micro 
  parameters:
    fullnameOverride: mongodb-03
    auth:
      rootPassword: master77!!
      database: sysk8s
      username: user
      password: master77!!
    service:
      port: 27000
    global:
      imageRegistry: "registry.systeer.com"

