apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mongodb-sharded-03
  namespace: mongodb-sharded
spec:
  clusterServiceClassExternalName: mongodb-sharded 
  clusterServicePlanExternalName: micro 
  parameters:
    fullnameOverride: mongodb-sharded-03
    mongodbRootPassword: 'master77!!'
    service:
      port: 27000
    global:
      imageRegistry: "registry.systeer.com"

