apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: kafka-03
  namespace: urimprjdemo001 
spec:
  clusterServiceClassExternalName: kafka
  clusterServicePlanExternalName: micro 
  parameters:
    fullnameOverride: kafka-03
    externalAccess:
      service:
        domain: "112.175.114.168"

