apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: postgresql-ha-03
  namespace: postgresql-ha
spec:
  clusterServiceClassExternalName: postgresql-ha
  clusterServicePlanExternalName: micro 
  parameters:
    fullnameOverride: postgresql-ha-03
    postgresql:
      password: master77!!
      database: sysk8s
    service:
      port: 5433

