apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: postgresql-03
  namespace: postgresql
spec:
  clusterServiceClassExternalName: postgresql 
  clusterServicePlanExternalName: micro 
  parameters:
    fullnameOverride: postgresql-03
    auth:
      postgresPassword: master77!!
      database: sysk8s
    global:
      postgresql:
        service:
          ports:
            postgresql: 5433
      imageRegistry: "registry.systeer.com"

