## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 

podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
resources:
  requests:
    memory: 4Gi
    cpu: 2000m
  limits:
    memory: 8Gi
    cpu: 4000m
livenessProbe:
  failureThreshold: 50
  initialDelaySeconds: 210
  periodSeconds: 210
readinessProbe:
  failureThreshold: 50
  initialDelaySeconds: 210
  periodSeconds: 210

service:
  type: NodePort

mariadb:
  enabled: true
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }
  resources:
    requests:
      memory: 4Gi
      cpu: 2000m
    limits:
      memory: 8Gi
      cpu: 4000m
  persistence:
    size: 16G

postgresql:
  enabled: false

