
controller:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "demand_backend_metallb_controller" }
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 192Mi
      cpu: 150m
  service:
    type: NodePort
    
speaker:
  podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "demand_backend_metallb_speaker" }
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 192Mi
      cpu: 150m
  service:
    type: NodePort





