## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

kubeVersion: 1.20-11 

podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }

replicaCount: 1 

service:
  type: NodePort
  port: 5672

resources:
  requests:
    memory: 1000Mi
    cpu: 500m
  limits:
    memory: 2000Mi 
    cpu: 1000m

persistence:
  size: 8Gi
