## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
kubeVersion: 1.20-11

architecture : replication 

master:
  podLabels: { "app":"monitoring-collector", "platform":"platform_service", "taskse":"service_catalog", "taskcl":"backend_service" }
  resources:
    requests:
      memory: 1Gi 
      cpu: 500m
  service:
    type: NodePort

replica:
  podLabels: { "app":"monitoring-collector", "platform":"platform_service", "taskse":"service_catalog", "taskcl":"backend_service" }
  replicaCount: 3
  resources:
    requests:
      memory: 1Gi
      cpu: 500m

