## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
kubeVersion: 1.20-11

podLabels: { "platform":"demand_service", "taskse":"demand_service_catalog", "taskcl": "backend_service" }

replicaCount: 2 

service:
  type: NodePort
  port: 5672

resources:
  requests:
    memory: 2000Mi 
    cpu: 1000m
  limits:
    memory: 4000Mi 
    cpu: 2000m

persistence:
  size: 16Gi

